# Generated by Django 5.1 on 2026-09-10 18:06

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('osm', 'OpenStreetMap'), ('manual', 'Manual Entry'), ('import', 'Imported'), ('cadastral', 'Cadastral Data')], default='osm', max_length=20)),
                ('osm_id', models.BigIntegerField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('height', models.FloatField(blank=True, null=True)),
                ('floors', models.IntegerField(blank=True, null=True)),
                ('height_source', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='projects.project')),
            ],
        ),
    ]
